version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # D2L Ignore All
      - dependency-name: "*"
      # Dependabot isn't able to update this packages that do not match the source, so anything with a version
      - dependency-name: "*.v*"
    commit-message:
      prefix: "fix:"
