---
name: "Semantic PR and Commit Messages"

# Disabled in the D2L fork (third party actions cannot be run in this repo)
on:
  workflow_dispatch:

jobs:
  semantic:
    uses: influxdata/validate-semantic-github-messages/.github/workflows/semantic.yml@main
    with:
      CHECK_PR_TITLE_OR_ONE_COMMIT: true

